backend:
  name: git-gateway
  branch: main

display_url: https://maasogluhukuk.netlify.app/
logo_url: https://maasogluhukuk.app/logo.svg

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "articles"
    label: "Makaleler"
    folder: "_articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayın Tarihi", name: "date", widget: "datetime"}
      - {label: "Kapak Fotoğrafı", name: "thumbnail", widget: "image", required: false}
      - {label: "Kısa Açıklama", name: "description", widget: "text", required: false}
      - {label: "İçerik", name: "body", widget: "markdown"}