backend:
  name: git-gateway
  branch: main # Deponuzun ana dalı 'main' ise böyle bırakın, 'master' ise 'master' yapın.

media_folder: "assets/images/uploads" # Yüklenecek resimlerin kaydedileceği yer
public_folder: "/assets/images/uploads" # Sitede resimlerin görüneceği yol

collections:
  - name: "articles" # Koleksiyonun adı
    label: "Makaleler" # Panelde görünecek etiket
    folder: "_articles" # Makalelerin kaydedileceği klasör
    create: true # Yeni makale eklemeye izin ver
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Dosya adı formatı
    fields: # Makale eklerken doldurulacak alanlar
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayın Tarihi", name: "date", widget: "datetime"}
      - {label: "Kapak Fotoğrafı", name: "thumbnail", widget: "image", required: false}
      - {label: "Kısa Açıklama", name: "description", widget: "text", required: false}
      - {label: "İçerik", name: "body", widget: "markdown"}